version: '3'
services:
  web:
    image: 'caching-server'
    build: './server'
    volumes:
      - './server:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - 'MONGO_URL=mongodb://mongo/caching'
      - 'PORT=5000'
      - 'GOOGLE_ID'
      - 'GOOGLE_SECRET'
    ports:
      - '5000:5000'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
  adminmongo:
    image: 'mrvautin/adminmongo'
    ports:
      - '1234:1234'
    environment:
      - 'HOST=0.0.0.0'
